src/Entity/Film.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FilmRepository")
 */
class Film
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $code;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_sortie;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $lien_film;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $genre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $directeurs;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $restriction;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Seance", mappedBy="film")
     */
    private $seance;

    /**
     * @ORM\Column(type="boolean")
     */
    private $fresh;

    public function __construct()
    {
        $this->seance = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDateSortie(): ?\DateTimeInterface
    {
        return $this->date_sortie;
    }

    public function setDateSortie(?\DateTimeInterface $date_sortie): self
    {
        $this->date_sortie = $date_sortie;

        return $this;
    }
    
    public function getLienFilm(): ?string
    {
        return $this->lien_film;
    }

    public function setLienFilm(string $lien_film): self
    {
        $this->lien_film = $lien_film;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getDirecteurs(): ?string
    {
        return $this->directeurs;
    }

    public function setDirecteurs(?string $directeurs): self
    {
        $this->directeurs = $directeurs;

        return $this;
    }

    public function getRestriction(): ?string
    {
        return $this->restriction;
    }

    public function setRestriction(?string $restriction): self
    {
        $this->restriction = $restriction;

        return $this;
    }

    /**
     * @return Collection|Seance[]
     */
    public function getSeance(): Collection
    {
        return $this->seance;
    }

    public function addSeance(Seance $seance): self
    {
        if (!$this->seance->contains($seance)) {
            $this->seance[] = $seance;
            $seance->setFilm($this);
        }

        return $this;
    }

    public function removeSeance(Seance $seance): self
    {
        if ($this->seance->contains($seance)) {
            $this->seance->removeElement($seance);
            // set the owning side to null (unless already changed)
            if ($seance->getFilm() === $this) {
                $seance->setFilm(null);
            }
        }

        return $this;
    }

    public function getFresh(): ?bool
    {
        return $this->fresh;
    }

    public function setFresh(bool $fresh): self
    {
        $this->fresh = $fresh;

        return $this;
    }


}

src/Controller/FilmController.php
<?php

namespace App\Controller;

use App\Repository\FilmRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class FilmController extends AbstractController
{
    /**
     * @Route("/film/{id<\d+>}", name="film")
     */
    public function index(FilmRepository $filmRepository, int $id)
    {
        $film = $filmRepository->find($id);
        //dump($film);

        return $this->render('film/index.html.twig', [
            'film' => $film,
        ] );
    }
}

templates/film/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Film{% endblock %}

{% block body %}
<style>
    body {
        background-color: darkgray;
    }

    .example-wrapper {
        margin: 1em auto;
        max-width: 800px;
        width: 95%;
        font: 18px/1.5 sans-serif;
    }

    .example-wrapper code {
        background: #F5F5F5;
        padding: 2px 6px;
    }

    .card {
        margin: 0 auto;
        border: 2px solid dimgrey;
        width: 70%;
        box-shadow: 10px 5px 5px black;
        background: #0f6674;
    }

    a {
        display: inline-block;
    }

    .btn-lg {
        font-size: 1.5rem;
    }


    div.button_align {
        margin: 10px 2.5% 10px 2.5%;
        text-align: center;
    }

    h1 {
        text-align: center;
    }

    h1,
    h2 {
        color: #313131;
    }

    img {
        max-width: 100%;
    }

    .card {
        padding: 1rem;
    }


    /*.btn-lg{margin: 0 auto;font-size: 2.5rem} */
</style>

<div class="example-wrapper">

    <div class="card">
        <div class="card-body">
            <h1 class="card-text">{{  film.titre  }}</h1>
        </div>
        <img src="{{ asset( film.image ) }}" alt="affiche">
        <div class="card-body">
            <h2 class="card-text">Réalisateur : </h2>
            <p class="card-text">{{ film.directeurs }}</p>
            <h2 class="card-text">Genre : </h2>
            <p class="card-text">{{ film.genre }}</p>
            <h2 class="card-text">Fiche complète : </h2>
            <p class="card-text">
                <a href="{{ film.lienFilm }}">{{ film.titre }}</a>
            </p>
            <div class="button_align">
                <a href="{{ path( 'voir_seance', {code :film.code}) }}" class="btn btn-lg btn-warning " > Voir les seances</a>
            </div>


        </div>
    </div>

</div>
{% endblock %}